In [6]:
import numpy as np
arr1 = np.arange(0,11)
arr2 = np.arange(1,12)
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11]


In [7]:
# Add/Substract/Multiply/Divide corresponding array elements of 2 (or more) NumPy vectors or matrices -
# Note - The vectors / matrices should be of the same size.
arr3 = arr1 + arr2
print(arr3)
arr3 = arr1 - arr2
print(arr3)
arr3 = arr1 * arr2
print(arr3)
arr3 = arr1 / arr2
print(arr3)

[ 1  3  5  7  9 11 13 15 17 19 21]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[  0   2   6  12  20  30  42  56  72  90 110]
[0.         0.5        0.66666667 0.75       0.8        0.83333333
 0.85714286 0.875      0.88888889 0.9        0.90909091]


In [8]:
# Add/Substract/Multiply/Divide/Exponent a scalar to all the array elements of a NumPy vector or matrix -
arr3 = arr1 + 2
print(arr3)
arr3 = arr1 - 2
print(arr3)
arr3 = arr1 * 2
print(arr3)
arr3 = arr1 / 2
print(arr3)
arr3 = arr1 ** 2
print(arr3)
arr_2d = np.arange(100).reshape(10,10)
arr3 = arr_2d + 10
print(arr3)

[ 2  3  4  5  6  7  8  9 10 11 12]
[-2 -1  0  1  2  3  4  5  6  7  8]
[ 0  2  4  6  8 10 12 14 16 18 20]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[  0   1   4   9  16  25  36  49  64  81 100]
[[ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]]


In [4]:
# Plain python me jab 0 se divide kro to zeorDivisionError milta he
# But NumPy me,
# -> (-ive_num not 0) / 0 = (-inf)
# -> (+ive_num not 0) / 0 = (inf)
# -> 0 / 0 = nan = not a number (null ke jaisa hi samajh lo)

arr1 = [-x for x in range(10) if x%2!=0]
arr2 = [x for x in range(10) if x%2==0]
arr3 = arr1 + arr2
print(arr3)
np.array(arr3) / np.zeros(10)

[-1, -3, -5, -7, -9, 0, 2, 4, 6, 8]


<ipython-input-4-cfe93cc904d8>:11: RuntimeWarning: divide by zero encountered in true_divide
  np.array(arr3) / np.zeros(10)
<ipython-input-4-cfe93cc904d8>:11: RuntimeWarning: invalid value encountered in true_divide
  np.array(arr3) / np.zeros(10)


array([-inf, -inf, -inf, -inf, -inf,  nan,  inf,  inf,  inf,  inf])

In [17]:
# Some Mathematical Array functions offered by NumPy -

arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# Square root -
np.sqrt(arr) # takes the square root of all the elements and then returns the corresponding values in an array of the same size.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
# Exponentiation (e^(array element)) -
np.exp(arr) # takes the exponent of all the elements and then returns the corresponding values in an array of the same size.

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [13]:
# Obtain maximum value (pehle kar chuke he)
np.max(arr)
# arr.max() -> previous

9

In [14]:
# Sin -
np.sin(arr) # takes the sine of all the elements and then returns the corresponding values in an array of the same size.

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
# Cos -
np.cos(arr) # takes the cosine of all the elements and then returns the corresponding values in an array of the same size.

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [20]:
# Natural Log (base e wala) -
np.log(arr)
# np.log(np.exp(arr))

<ipython-input-20-95244240851d>:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [21]:
# Base 2 log -
np.log2(arr)

<ipython-input-21-77b4515e3fc8>:2: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ,
       3.32192809])

In [22]:
# Base 10 log -
np.log10(arr)

<ipython-input-22-bf6952c6516e>:2: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        ])

In [23]:
# Link - https://numpy.org/doc/stable/reference/ufuncs.html

In [ ]:
*******************************************************************************************************************************

In [30]:
# Some more array operations -

# 1. Take sum of all array elements -
# np.sum(a=arr_name_to_operated_on, axis=corresponding_to_the_dimension->optional, dtype=the_output_type_to_be_returned->optional)
# OR
# arr_name.sum(axis=corresponding_to_the_dimension->optional, dtype=the_output_type_to_be_returned->optional)
# axis corresponds to the dimension along which we want to sum, for column axis=0, for row axis=1.

# # Regular way to calc column wise sum -
# # col_sum = [mat[:,i].sum() for i in range(5)]
# # col_sum = np.array(col_sum)
# # col_sum

# # Mentos way to calc column wise sum -
# mat.sum(axis=0)

arr = np.arange(1,10).reshape(3,3)
print(arr)
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [ ]:
# 2. Take standard deviation of all the values present in an array - arr_name.std()
# isme bhi axis wali cheez hoti he.
# axis = 0 -> column 
# axis = 1 -> row