In [2]:
# NumPy is a Linear Algebra library for python. Its used in almost all the other libraries in the PyData ecosystem.

In [4]:
# Hum NumPy ko use karenge using its NumPy arrays, which are of 2 types -
# 1. Vectors - 1D arrays - 1D List
# 2. Matrices - 2D arrays - 2D List

In [55]:
import numpy as np

# Casting a python 1D list to a numpy vector -
arr_list = [1,2,3]
arr_vector = np.array(arr_list)
print(arr_vector)

# Casting a python 2D list to a numpy matrix -
arr_list_of_list = [[1,2,3],[4,5,6],[7,8,9]]
arr_matrix = np.array(arr_list_of_list)
print(arr_matrix)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Faster way to do the above is using inbuilt generation methods of NumPy -
# arange() method - "A range" method, functionality wise its same as the range method of python
# python ka range generates a list whereas the arange() method generates a NumPy vector. 
numpy_vector = np.arange(1,11)
print(numpy_vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
vec1 = np.arange(0,11,3) # arange(start(included), stop(excluded), step size(default=1))
print(vec1)

[0 3 6 9]


In [15]:
# Genereating some special NumPy vectors and matrices -

# Vector filled with zeros
vec_0s = np.zeros(5)
print(vec_0s)

# Matrix filled with zeros
mat_0s = np.zeros((2,3))
# zeros((rows,columns)) -> (rows,columns) ki ek tuple dete he.
print(mat_0s)

# Vector filled with ones
vec_1s = np.ones(3)
print(vec_1s)

# Matrix filled with ones
mat_1s = np.ones((4,6))
# zeros((rows,columns)) -> (rows,columns) ki ek tuple dete he.
print(mat_1s)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
# Generate n (including p and q) decimal numbers in a given range = [p,q]
# np.linspace(p,q,n) --> returns a 1D list of these n numbers.
print(np.linspace(1,5,100))

[1.         1.04040404 1.08080808 1.12121212 1.16161616 1.2020202
 1.24242424 1.28282828 1.32323232 1.36363636 1.4040404  1.44444444
 1.48484848 1.52525253 1.56565657 1.60606061 1.64646465 1.68686869
 1.72727273 1.76767677 1.80808081 1.84848485 1.88888889 1.92929293
 1.96969697 2.01010101 2.05050505 2.09090909 2.13131313 2.17171717
 2.21212121 2.25252525 2.29292929 2.33333333 2.37373737 2.41414141
 2.45454545 2.49494949 2.53535354 2.57575758 2.61616162 2.65656566
 2.6969697  2.73737374 2.77777778 2.81818182 2.85858586 2.8989899
 2.93939394 2.97979798 3.02020202 3.06060606 3.1010101  3.14141414
 3.18181818 3.22222222 3.26262626 3.3030303  3.34343434 3.38383838
 3.42424242 3.46464646 3.50505051 3.54545455 3.58585859 3.62626263
 3.66666667 3.70707071 3.74747475 3.78787879 3.82828283 3.86868687
 3.90909091 3.94949495 3.98989899 4.03030303 4.07070707 4.11111111
 4.15151515 4.19191919 4.23232323 4.27272727 4.31313131 4.35353535
 4.39393939 4.43434343 4.47474747 4.51515152 4.55555556 4.595959

In [20]:
# Generate an Identity Matrix (leading diagonal pe 1s wali square matrix) -
identity_mat = np.eye(5)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
# Genrate a vector filled with random decimal numbers from [0,1] -
print(np.random.rand(5))

# Genrate a matrix filled with random decimal numbers from [0,1] -
print(np.random.rand(5,6))

# IMPORTANT - Numbers generated using rand() method follow Uniform Distribution.

[0.8332115  0.91006954 0.01296187 0.92161817 0.93687163]
[[0.5798884  0.51662881 0.17444099 0.31926187 0.00360072 0.44407867]
 [0.55223108 0.20226315 0.85061438 0.54368819 0.77115373 0.0116302 ]
 [0.01991697 0.62576088 0.04293496 0.42161499 0.07214546 0.0606923 ]
 [0.58179777 0.73691758 0.7457853  0.72134357 0.6036778  0.22139597]
 [0.27970338 0.38112042 0.72772548 0.71335615 0.86592967 0.99224165]]


In [27]:
# If we want to generate a vector of random numbers that follow Standard Normal / Gaussian Distribution, centered around 0 (mean is 0) -
print(np.random.randn(5))

# If we want to generate a matrix of random numbers that follow Standard Normal / Gaussian Distribution, centered around 0 (mean is 0) -
print(np.random.randn(5,6))

[ 0.03655238  1.25587419 -0.97946369  0.6147711   1.200769  ]
[[ 0.53593905  1.00082976 -0.40896642  0.3270343   0.26187579  0.63409275]
 [-0.51435193 -1.70617076  1.40229023 -1.61874104  0.14180202  0.53106904]
 [ 1.7097707   0.28654781 -0.87563774  1.51964185 -0.98176517  1.33274983]
 [-0.60584223 -0.82610256 -0.07693264  0.72196761  0.64574342  1.99534414]
 [ 0.1098121   0.97085313  1.32264928  2.10598004 -0.5054779   0.08506406]]


In [28]:
# If we want to generate a vector of random Integers -
print(np.random.randint(1,100,10)) # (low (included), high(excluded), kitne generate karne he)

[13 94 34 33 27 35 64 42 94 41]


In [31]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr_int = np.random.randint(0,11,5)
arr_int

array([3, 9, 4, 1, 0])

In [43]:
# Resize an array - meaning data stored in it would be of same type ie random ints, randn etc but the number of
# elements would be changed, 1d to 2d and vice versa is also possible.

# Reshaping arr - array_name.reshape(new_size)
# IMP - Total Number of Elements should be SAME. 25 = 5*5
arr = arr.reshape(5,5) # arr ko reshape karke ussi identifier pe assign kar diya.
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [44]:
# To find the maximum / minimum element of a NumPy vector or matrix -
# array_name.max(), array_name.min()
print(arr_int.max())
print(arr_int.min())
print(arr.max())
print(arr.min())

9
0
24
0


In [47]:
# To find the index of maximum / minimum element of a NumPy vector (array) -
# array_name.argmax(),array_name.argmin()
print(arr_int)
print(arr_int.argmax())
print(arr_int.argmin())
print(arr)
print(arr.argmax())
print(arr.argmin())

[3 9 4 1 0]
1
4
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
24
0


In [51]:
# To get the size / dimesions of vector or matrix -
print(arr_int.shape)
print(arr.shape)

(5,)
(5, 5)


In [53]:
# To get the datatype of items in a vector or matrix -
print(arr.dtype)
print(arr_int.dtype)

int32
int32


In [58]:
# np.random.randint() pura likhne ki jagah -
from numpy.random import randint
print(randint(0,11,5)) # seedha chal jaega

from numpy.random import rand as rn
print(rn(10))

[ 0  4  2 10  5]
[0.53066328 0.98868439 0.35577253 0.45375425 0.54021989 0.62013388
 0.53841203 0.67421857 0.44679941 0.13347344]
